import Head from "next/head";
import NavBar from "../components/NavBar";
import Hero from "../components/Hero";
import Products from "../components/Products";

const Home = () => {
  return (
    <div>
      <Head>
        <title>Christian Religious Item Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <NavBar />
        <Hero />
        <Products />
      </main>
    </div>
  );
};

export default Home;
